### ISSUE TITLE
Outlier Detection Function Docstring

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/eazieda#3]

**Comment by vigneshRajakumar** [comment]
This is the function definition I have in mind for this function:

```python
def outliers(df, method = "z-score", remove = False)
```

There are a bunch of different ways to spot and remove outliers, with z-scores being a pretty common one.  I also added a boolean to remove outliers in place if needed. 

The function itself will return a series (/dataframe?) of the outliers
