### ISSUE TITLE
Solicit Feedback from TA

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/eazieda#73]
Touch base with TA to get rough feedback on anything we need to update.

**Comment by vigneshRajakumar** [comment]
> Small typos in README: checking *for* missing values, *plotting* Won't the `outliers_remove` example give indices (6,7) rather than (0,1)? "My PR" is a bad name for a pull request, I would also suggest starting a new branch for new features rather than constantly merging from master

Summarizing

- [ ] Use descriptive names for PR's
- [ ] Make a new branch for each feature
- [ ] Fix typos in README #75 
- [x] Review example for `outliers_remove` #76
